#!/bin/bash

###################################################################################
#rj name=zzztest
#rj nodes=1
#rj queue=anu_8501
#rj taskspernode=1
#rj features=v100

msg() { printf "$*\n" >&2; }
die() { msg "!!! $*"; exit 1; }
log() { msg "### $*"; }

module purge
module load openmpi/4.1.3-mlnx-gcc
module unload cuda/11.3.1
module load anaconda3
module load cuda/11.2
module load gcc/9.2.0
module list

cd "/data/anu_8501/anu_u7533680/"

export HTTPS_PROXY=http://proxy.per.dug.com:3128
export HTTP_PROXY=http://proxy.per.dug.com:3128
export https_proxy=http://proxy.per.dug.com:3128
export http_proxy=http://proxy.per.dug.com:3128

echo ". /d/sw/anaconda3/5.2/etc/profile.d/conda.sh" >> ~/.bashrc
source ~/.bashrc


##################################################################################
cd mmpose
conda activate openmmlab
echo "### Activated conda env"


python demo/topdown_demo_with_mmdet.py demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth configs/animal_2d_keypoint/topdown_heatmap/animalpose/td-hm_hrnet-w32_8xb64-210e_animalpose-256x256.py https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_animalpose_256x256-1aa7f075_20210426.pth --input tests/data/animalpose/ca110.jpeg --output-root vis_results --draw-heatmap --det-cat-id=15